version: "3.9"
services:
  backend:
    container_name: kupipodariday-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: image-kupipodariday-api
    ports:
      - "4000:3000"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: .env
    image: image-kupipodariday-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  postgres:
    container_name: app-postgress
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/data/postgres

volumes:
  postgres_data:
